#CI for test task from DoctorWeb
stages:
    - build
    - deploy
    
#Build from source files <<epm>> ----->>> with help Dockerfile
build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

#Deploy ready application from DockerHub
deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
     - docker run skensel/epm
